Repository Ashwinshankar98/ClassMateBot, pull requests merged in 2021-11, with the labels that each got.

#27 Feature ashwin
  bot.py
  cogs/dm.py
Labels: enhancement

#48 Kaushik changes
  cogs/deadline.py
Labels: bug, enhancement

#50 Attendance
  cogs/cal_attendance.py
  cogs/qanda.py
  data/qanda/qandastorage.json
  test/test_bot.py
Labels: bug, enhancement, testing bug

#55 Codecov
  cogs/cal_attendance.py
  test/test_bot.py
Labels: bug, enhancement

#62 Profanity branch
  cogs/profanity.py
  requirements.txt
  test/test_bot.py
Labels: bug, enhancement, testing bug

#66 Ashwin
  bot.py
  cogs/banUsers.py
  cogs/charts.py
  cogs/cogMaintenance.py
  cogs/deadline.py
  cogs/email_address_spec.py
  cogs/links.py
  cogs/newComer.py
  cogs/pinning.py
  cogs/qanda.py
  cogs/userRanking.py
  cogs/voting.py
Labels: enhancement

#67 Added docs for new features
  README.md
  docs/DM/Private_msg.md
  docs/DM/group_reminder.md
  docs/Instructors/Get_Instructor.md
  docs/Instructors/Remove_Instructor.md
  docs/Instructors/Set_Instructor.md
  docs/Iteration2Features.md
  docs/Profanity/profanity.md
  docs/Q and A/answer.md
  docs/Q and A/ask.md
  docs/Q and A/ask_anonymous.md
  docs/TA/Get_TA.md
  docs/TA/Remove_TA.md
  docs/TA/Set_TA.md
Labels: documentation

#72 Attend bug
  cogs/cal_attendance.py
  test/test_bot.py
Labels: testing bug
